/* Programs embedded in the review page. Expected output is what Java prints. */
(function (root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.ReviewSamples = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const samples = {
    averageBroken: {
      label: "Average.java",
      input: "",
      error: /;/,
      code: [
        "public class Average {",
        "    public static void Main(String[] args) {",
        "        int total = 7 + 8 + 10",
        "        System.out.println(\"Average: \" + total / 3);",
        "    }",
        "}"
      ].join("\n")
    },
    averageFixed: {
      label: "Average.java",
      input: "",
      output: ["Average: 8", "Average: 8.333333333333334", ""].join("\n"),
      code: [
        "public class Average {",
        "    public static void main(String[] args) {",
        "        int total = 7 + 8 + 10;",
        "        System.out.println(\"Average: \" + total / 3);",
        "        System.out.println(\"Average: \" + total / 3.0);",
        "    }",
        "}"
      ].join("\n")
    },
    distance: {
      label: "Distance.java",
      input: "",
      output: ["5", "5", "0", "6", "-5", "5", ""].join("\n"),
      code: [
        "public class Distance {",
        "    // Only zero tests and subtracting 1. Both inputs should be >= 0.",
        "    public static int distance(int a, int b) {",
        "        int i = a;",
        "        int j = b;",
        "        while (i != 0 && j != 0) {",
        "            i = i - 1;",
        "            j = j - 1;",
        "        }",
        "        if (i == 0) {",
        "            return j;",
        "        } else {",
        "            return i;",
        "        }",
        "    }",
        "",
        "    public static int distanceAlt(int a, int b) {",
        "        if (a >= b) {",
        "            return a - b;",
        "        } else {",
        "            return b - a;",
        "        }",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(distance(3, 8));",
        "        System.out.println(distance(8, 3));",
        "        System.out.println(distance(4, 4));",
        "        System.out.println(distance(0, 6));",
        "        System.out.println(distance(-2, 3));",
        "        System.out.println(distanceAlt(-2, 3));",
        "    }",
        "}"
      ].join("\n")
    },
    arith: {
      label: "Arith.java",
      input: "",
      output: ["15", "18", "2", "4", "1", "4", "-5", "-3", "96", "456", "411", ""].join("\n"),
      code: [
        "public class Arith {",
        "    public static void main(String[] args) {",
        "        System.out.println(3 + 6 * 2);",
        "        System.out.println(20 - 6 % 4);",
        "        System.out.println((20 - 6) % 4);",
        "        System.out.println(17 / 4);",
        "        System.out.println(17 % 4);",
        "        System.out.println(4 % 17);",
        "        System.out.println(-23 / 4);",
        "        System.out.println(-23 % 4);",
        "        System.out.println(4 + 5 + \"6\");",
        "        System.out.println(\"4\" + 5 + 6);",
        "        System.out.println(\"4\" + (5 + 6));",
        "    }",
        "}"
      ].join("\n")
    },
    doubles: {
      label: "Doubles.java",
      input: "",
      output: [
        "0.30000000000000004",
        "0.09999999999999998",
        "3",
        "3.5",
        "3.0",
        "2147483647",
        "-2147483648",
        ""
      ].join("\n"),
      code: [
        "public class Doubles {",
        "    public static void main(String[] args) {",
        "        System.out.println(0.1 + 0.2);",
        "        System.out.println(1.0 - 0.9);",
        "        System.out.println(7 / 2);",
        "        System.out.println(7 / 2.0);",
        "        double half = 7 / 2;",
        "        System.out.println(half);",
        "        int big = Integer.MAX_VALUE;",
        "        System.out.println(big);",
        "        System.out.println(big + 1);",
        "    }",
        "}"
      ].join("\n")
    },
    shorts: {
      label: "Shorts.java",
      input: "",
      output: ["true", "check 2", "false", "false", "check 4", "true", ""].join("\n"),
      code: [
        "public class Shorts {",
        "    public static boolean check(int n) {",
        "        System.out.println(\"check \" + n);",
        "        return n > 2;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(5 > 3 || check(1));",
        "        System.out.println(5 < 3 || check(2));",
        "        System.out.println(5 < 3 && check(3));",
        "        System.out.println(5 > 3 && check(4));",
        "    }",
        "}"
      ].join("\n")
    },
    gradeWrong: {
      label: "GradeWrong.java",
      input: "95",
      output: ["A", "B", "C", ""].join("\n"),
      code: [
        "import java.util.Scanner;",
        "",
        "public class GradeWrong {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int score = in.nextInt();",
        "        if (score >= 90) {",
        "            System.out.println(\"A\");",
        "        }",
        "        if (score >= 80) {",
        "            System.out.println(\"B\");",
        "        }",
        "        if (score >= 70) {",
        "            System.out.println(\"C\");",
        "        } else {",
        "            System.out.println(\"F\");",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    gradeRight: {
      label: "Grade.java",
      input: "95",
      output: "A\n",
      code: [
        "import java.util.Scanner;",
        "",
        "public class Grade {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int score = in.nextInt();",
        "        if (score >= 90) {",
        "            System.out.println(\"A\");",
        "        } else if (score >= 80) {",
        "            System.out.println(\"B\");",
        "        } else if (score >= 70) {",
        "            System.out.println(\"C\");",
        "        } else {",
        "            System.out.println(\"F\");",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    gradeReturn: {
      label: "GradeReturn.java",
      input: "",
      output: ["A", "B", "C", "F", ""].join("\n"),
      code: [
        "public class GradeReturn {",
        "    public static String grade(int score) {",
        "        if (score >= 90) {",
        "            return \"A\";",
        "        }",
        "        if (score >= 80) {",
        "            return \"B\";",
        "        }",
        "        if (score >= 70) {",
        "            return \"C\";",
        "        }",
        "        return \"F\";",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(grade(95));",
        "        System.out.println(grade(85));",
        "        System.out.println(grade(70));",
        "        System.out.println(grade(50));",
        "    }",
        "}"
      ].join("\n")
    },
    branch: {
      label: "Branch.java",
      input: "",
      output: ["1", "2", "4", "5", "7", ""].join("\n"),
      code: [
        "public class Branch {",
        "    public static void main(String[] args) {",
        "        int i = 0;",
        "        while (i < 12) {",
        "            i = i + 1;",
        "            if (i % 3 == 0) {",
        "                continue;",
        "            }",
        "            if (i == 8) {",
        "                break;",
        "            }",
        "            System.out.println(i);",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    digits: {
      label: "Digits.java",
      input: "",
      output: ["14", "5", "0", "27", ""].join("\n"),
      code: [
        "public class Digits {",
        "    public static int sumDigits(int n) {",
        "        int sum = 0;",
        "        while (n != 0) {",
        "            sum = sum + n % 10;",
        "            n = n / 10;",
        "        }",
        "        return sum;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(sumDigits(1904));",
        "        System.out.println(sumDigits(5));",
        "        System.out.println(sumDigits(0));",
        "        System.out.println(sumDigits(999));",
        "    }",
        "}"
      ].join("\n")
    },
    gcd: {
      label: "Gcd.java",
      input: "",
      output: ["6", "3", "7", "1", ""].join("\n"),
      code: [
        "public class Gcd {",
        "    // Both inputs should be >= 1.",
        "    public static int gcd(int a, int b) {",
        "        while (a != b) {",
        "            if (a > b) {",
        "                a = a - b;",
        "            } else {",
        "                b = b - a;",
        "            }",
        "        }",
        "        return a;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(gcd(12, 18));",
        "        System.out.println(gcd(21, 6));",
        "        System.out.println(gcd(7, 7));",
        "        System.out.println(gcd(9, 4));",
        "    }",
        "}"
      ].join("\n")
    },
    increases: {
      label: "Increases.java",
      input: "3 5 2 8 9 -1",
      output: "3\n",
      code: [
        "import java.util.Scanner;",
        "",
        "public class Increases {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int prev = in.nextInt();",
        "        int cur = in.nextInt();",
        "        int count = 0;",
        "        while (cur != -1) {",
        "            if (cur > prev) {",
        "                count = count + 1;",
        "            }",
        "            prev = cur;",
        "            cur = in.nextInt();",
        "        }",
        "        System.out.println(count);",
        "    }",
        "}"
      ].join("\n")
    },
    oddsWhile: {
      label: "OddsDown.java",
      input: "4",
      output: ["3", "1", ""].join("\n"),
      code: [
        "import java.util.Scanner;",
        "",
        "public class OddsDown {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int i = in.nextInt();",
        "        while (i >= -5) {",
        "            if (i % 2 == 1) {",
        "                System.out.println(i);",
        "            }",
        "            i--;",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    oddsFor: {
      label: "OddsDownFor.java",
      input: "4",
      output: ["3", "1", ""].join("\n"),
      code: [
        "import java.util.Scanner;",
        "",
        "public class OddsDownFor {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        for (int i = in.nextInt(); i >= -5; i--) {",
        "            if (i % 2 == 1) {",
        "                System.out.println(i);",
        "            }",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    oddsStep: {
      label: "OddsStep.java",
      input: "4",
      output: ["3", "1", "-1", "-3", "-5", ""].join("\n"),
      code: [
        "import java.util.Scanner;",
        "",
        "public class OddsStep {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int j = in.nextInt();",
        "        if (j % 2 == 0) {",
        "            j = j - 1;",
        "        }",
        "        for (; j >= -5; j = j - 2) {",
        "            System.out.println(j);",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    ternary: {
      label: "OddsTernary.java",
      input: "4",
      output: ["3", "1", "-1", "-3", "-5", ""].join("\n"),
      code: [
        "import java.util.Scanner;",
        "",
        "public class OddsTernary {",
        "    public static void main(String[] args) {",
        "        Scanner in = new Scanner(System.in);",
        "        int n = in.nextInt();",
        "        for (int j = n % 2 == 0 ? n - 1 : n; j >= -5; j = j - 2) {",
        "            System.out.println(j);",
        "        }",
        "    }",
        "}"
      ].join("\n")
    },
    doWhile: {
      label: "DoWhile.java",
      input: "",
      output: ["do-while:", "10", "while:", "done", ""].join("\n"),
      code: [
        "public class DoWhile {",
        "    public static void main(String[] args) {",
        "        int n = 10;",
        "        System.out.println(\"do-while:\");",
        "        do {",
        "            System.out.println(n);",
        "            n = n + 5;",
        "        } while (n < 10);",
        "",
        "        n = 10;",
        "        System.out.println(\"while:\");",
        "        while (n < 10) {",
        "            System.out.println(n);",
        "            n = n + 5;",
        "        }",
        "        System.out.println(\"done\");",
        "    }",
        "}"
      ].join("\n")
    },
    power: {
      label: "Power.java",
      input: "",
      output: ["81", "1024", "1", ""].join("\n"),
      code: [
        "public class Power {",
        "    // k should be >= 0.",
        "    public static int power(int base, int k) {",
        "        int result = 1;",
        "        int i = 0;",
        "        while (i < k) {",
        "            result = result * base;",
        "            i = i + 1;",
        "        }",
        "        return result;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(power(3, 4));",
        "        System.out.println(power(2, 10));",
        "        System.out.println(power(5, 0));",
        "    }",
        "}"
      ].join("\n")
    },
    c2f: {
      label: "C2F.java",
      input: "",
      output: ["212 212", "98 98", "2 1", "-40 -40", "69", ""].join("\n"),
      code: [
        "public class C2F {",
        "    public static int c2fFirstTry(int c) {",
        "        return c * 9 / 5 + 32;",
        "    }",
        "",
        "    public static int c2f(int c) {",
        "        return (c * 9 + 160) / 5;",
        "    }",
        "",
        "    public static void show(int c) {",
        "        System.out.println(c2fFirstTry(c) + \" \" + c2f(c));",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        show(100);",
        "        show(37);",
        "        show(-17);",
        "        show(-40);",
        "        System.out.println(37 * (9 / 5) + 32);",
        "    }",
        "}"
      ].join("\n")
    },
    clock: {
      label: "Clock.java",
      input: "",
      output: ["1:2:5", "0:0:59", "2:0:0", ""].join("\n"),
      code: [
        "public class Clock {",
        "    public static int hours(int s) {",
        "        return s / 3600;",
        "    }",
        "",
        "    public static int minutes(int s) {",
        "        return s % 3600 / 60;",
        "    }",
        "",
        "    public static int seconds(int s) {",
        "        return s % 60;",
        "    }",
        "",
        "    public static void show(int s) {",
        "        System.out.println(hours(s) + \":\" + minutes(s) + \":\" + seconds(s));",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        show(3725);",
        "        show(59);",
        "        show(7200);",
        "    }",
        "}"
      ].join("\n")
    },
    leap: {
      label: "Leap.java",
      input: "",
      output: ["true", "false", "false", "true", ""].join("\n"),
      code: [
        "public class Leap {",
        "    public static boolean isLeap(int y) {",
        "        return (y % 4 == 0 && y % 100 != 0) || y % 400 == 0;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(isLeap(2024));",
        "        System.out.println(isLeap(2023));",
        "        System.out.println(isLeap(1900));",
        "        System.out.println(isLeap(2000));",
        "    }",
        "}"
      ].join("\n")
    },
    reverse: {
      label: "Reverse.java",
      input: "",
      output: ["321", "21", "7", "504", ""].join("\n"),
      code: [
        "public class Reverse {",
        "    public static int reverse(int n) {",
        "        int rev = 0;",
        "        while (n != 0) {",
        "            rev = rev * 10 + n % 10;",
        "            n = n / 10;",
        "        }",
        "        return rev;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(reverse(123));",
        "        System.out.println(reverse(1200));",
        "        System.out.println(reverse(7));",
        "        System.out.println(reverse(405));",
        "    }",
        "}"
      ].join("\n")
    },
    exclusive: {
      label: "Exclusive.java",
      input: "",
      output: ["6", "5", "0", ""].join("\n"),
      code: [
        "public class Exclusive {",
        "    public static int count(int n) {",
        "        int c = 0;",
        "        int i = 1;",
        "        while (i <= n) {",
        "            boolean by3 = i % 3 == 0;",
        "            boolean by5 = i % 5 == 0;",
        "            if ((by3 || by5) && !(by3 && by5)) {",
        "                c = c + 1;",
        "            }",
        "            i = i + 1;",
        "        }",
        "        return c;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(count(15));",
        "        System.out.println(count(10));",
        "        System.out.println(count(1));",
        "    }",
        "}"
      ].join("\n")
    },
    prime: {
      label: "Prime.java",
      input: "",
      output: ["true", "false", "true", "false", "true", ""].join("\n"),
      code: [
        "public class Prime {",
        "    public static boolean isPrime(int n) {",
        "        if (n < 2) {",
        "            return false;",
        "        }",
        "        int d = 2;",
        "        while (d * d <= n) {",
        "            if (n % d == 0) {",
        "                return false;",
        "            }",
        "            d = d + 1;",
        "        }",
        "        return true;",
        "    }",
        "",
        "    public static void main(String[] args) {",
        "        System.out.println(isPrime(2));",
        "        System.out.println(isPrime(9));",
        "        System.out.println(isPrime(13));",
        "        System.out.println(isPrime(1));",
        "        System.out.println(isPrime(97));",
        "    }",
        "}"
      ].join("\n")
    }
  };

  return { samples: samples };
});
